// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "collections.getAllWithPinned", input: never, result: CollectionWithPinnedStatus[] } | 
        { key: "collections.getById", input: number, result: Collection | null } | 
        { key: "collections.getByUser", input: never, result: CollectionWithPinnedStatus[] } | 
        { key: "collections.getOnePinnedStatus", input: number, result: CollectionWithPinnedStatus | null } | 
        { key: "collections.getPinned", input: never, result: PinnedCollections[] } | 
        { key: "links.archiveStatByDate", input: string | null, result: ArchiveStatData } | 
        { key: "links.filterByTags", input: FilterByTagsArgs, result: FilterResult } | 
        { key: "links.getByCollection", input: number, result: LinkWithTags[] } | 
        { key: "links.getByDate", input: GetByDateArgs, result: LinkWithTags[] } | 
        { key: "links.getById", input: number, result: LinkWithTags | null } | 
        { key: "links.getByUser", input: never, result: LinkWithTags[] } | 
        { key: "links.getSummary", input: number, result: SummariesReturnData } | 
        { key: "links.searchByWord", input: SearchByNameArgs, result: FilterResult } | 
        { key: "tags.getByUser", input: never, result: Tag[] } | 
        { key: "users.get", input: never, result: User | null } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "collections.addPinned", input: number, result: PinnedUserCollections } | 
        { key: "collections.create", input: CreateCollectionArgs, result: Collection } | 
        { key: "collections.deleteOne", input: number, result: Collection } | 
        { key: "collections.editOne", input: EditCollectionArgs, result: Collection } | 
        { key: "links.create", input: CreateLinkArgs, result: Link } | 
        { key: "links.deleteOne", input: number, result: Link } | 
        { key: "links.editOne", input: EditLinkArgs, result: Link } | 
        { key: "tags.create", input: CreateTagArgs, result: Tag } | 
        { key: "tags.delete", input: number, result: Tag } | 
        { key: "tags.edit", input: UpdateTagArgs, result: Tag },
    subscriptions: never
};

export type CreateCollectionArgs = { name: string; color: string; pinned: boolean; public: boolean }

export type EditLinkArgs = { id: number; link_name: string; url: string; description: string | null; collection_id: number; new_tags: number[]; deleted_tags: number[]; archived: boolean }

export type CreateLinkArgs = { link_name: string; url: string; description: string | null; collection_id: number; tags: number[] }

export type SummariesData = { date: string; count: number }

export type LinkWithTags = { id: number; name: string; url: string; description: string; archived: boolean; ownerId: string; collectionId: number; createdAt: string; tags: { id: number; name: string; color: string }[] }

export type CollectionWithPinnedStatus = { id: number; name: string; description: string; color: string; isPublic: boolean; ownerId: string; createdAt: string; pinnedBy: { user: { id: string } }[] }

export type EditCollectionArgs = { id: number; name: string; color: string; pinned: boolean; public: boolean }

export type UpdateTagArgs = { tag_id: number; tag_name: string; color: string }

export type User = { id: string; created_at: string; updated_at: string; username: string; name: string; email: string; avatar: string | null; bio: string | null; connectedTG: boolean }

export type Tag = { id: number; name: string; color: string; ownerId: string }

export type FilterByTagsArgs = { mode: Mode; tags: number[]; take: number; skip: number }

export type PinnedCollections = { collection: Collection }

export type GetByDateArgs = { date: string; size: number | null }

export type ArchiveStatData = { total: number; archived: number; not_archived: number }

export type PinnedUserCollections = { userId: string; collectionId: number }

export type SearchMode = "Name" | "Description" | "Url"

export type SearchByNameArgs = { mode: SearchMode; word: string; collection_id: number | null; take: number; skip: number }

export type Collection = { id: number; name: string; description: string; color: string; isPublic: boolean; ownerId: string; createdAt: string }

export type SummariesReturnData = { total_links: number; max_links: number; summaries: SummariesData[][] }

export type Mode = "And" | "Or"

export type FilterResult = { total_links: number | null; links: LinkWithTags[] }

export type CreateTagArgs = { tag_name: string; color: string }

export type Link = { id: number; name: string; url: string; description: string; archived: boolean; ownerId: string; collectionId: number; createdAt: string }
