// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "collections.getById", input: number, result: Collection | null } | 
        { key: "collections.getByUser", input: never, result: Collection[] } | 
        { key: "collections.getPinned", input: never, result: PinnedCollections[] } | 
        { key: "links.archiveStatByDate", input: string | null, result: ArchiveStatData } | 
        { key: "links.getByDate", input: string, result: Link[] } | 
        { key: "links.getSummary", input: string | null, result: SummariesData[] } | 
        { key: "tags.getByUser", input: never, result: Tag[] } | 
        { key: "users.get", input: never, result: User | null } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "collections.addPinned", input: number, result: PinnedUserCollections } | 
        { key: "collections.create", input: CreateCollectionArgs, result: Collection } | 
        { key: "links.create", input: CreateLinkArgs, result: Link } | 
        { key: "tags.create", input: CreateTagArgs, result: Tag } | 
        { key: "tags.edit", input: UpdateTagArgs, result: Tag },
    subscriptions: never
};

export type CreateTagArgs = { tag_name: string }

export type Tag = { id: number; name: string; ownerId: string }

export type PinnedCollections = { collection: Collection }

export type CreateLinkArgs = { link_name: string; url: string; description: string | null; collection_id: number }

export type Link = { id: number; name: string; url: string; description: string; archived: boolean; ownerId: string; collectionId: number; createdAt: string }

export type PinnedUserCollections = { userId: string; collectionId: number }

export type ArchiveStatData = { total: number; archived: number; not_archived: number }

export type CreateCollectionArgs = { name: string; color: string; pinned: boolean; public: boolean }

export type SummariesData = { date: string; count: number }

export type UpdateTagArgs = { tag_id: number; tag_name: string }

export type Collection = { id: number; name: string; description: string; color: string; isPublic: boolean; ownerId: string; archivedLinks: number; totalLinks: number; createdAt: string }

export type User = { id: string; created_at: string | null; updated_at: string | null; username: string; name: string; email: string; avatar: string | null; bio: string | null; connectedTG: boolean }
